server:
  port: 8001


spring:
  application:
    name: microservicecloud-dept
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver           #mysql驅動包
    url: jdbc:mysql://localhost:3306/test?useSSL=false #資料庫名稱，請自訂
    username: root
    password: cxz123499
    validationQuery: SELECT 1
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect